cas:
  debug: true
  server-url: http://login.greathiit.com
  login-url: http://login.greathiit.com/login
  logout-url: http://login.greathiit.com/logout
  login-success-url: http://localhost:8090
  local-server-url: http://localhost:8080